project:
  type: website
  output-dir: docs

website:
  title: "Spatial Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects